empmanager/employee/urls.py
from django.urls import path
from . import views


app_name = 'employee'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('detail/patient/<int:pk>', views.IdPatientInfoDetailView.as_view(), name="idpatientinfo_detail")
]

empmanager/empmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('karte/', include('karte.urls')),
    path('patient/', include('patient.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empmanager/karte/urls.py
from django.urls import path
from . import views

app_name = 'karte'

urlpatterns = [
    path('',views.KarteInfoListView.as_view(), name='karteinfo_list'),
    path('create/', views.KarteInfoCreateView.as_view(), name = 'karteinfo_create'),
    path('create/patient', views.AddPatientCreateView.as_view(), name = 'addpatient_create'),
    path('detail/therapist/<int:pk>', views.TherapistKarteListDetailView.as_view(), name='therapistkartelist_detail'),
    path('detail/karteinfo/<int:pk>', views.KarteInfoDetailView.as_view(), name='karteinfo_detail'),
    path('detail/karte/<int:pk>', views.IdPatientKarteDetailView.as_view(), name="idpatientkarte_detail")
]

empmanager/karte/models.py
from django.db import models
from django.utils import timezone

from employee.models import Employee


class Pain(models.Model):
    name = models.CharField('痛みの具合', max_length=20)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name


class Range(models.Model):
    name = models.CharField('可動域制限', max_length=20)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name


class RehaPlan(models.Model):
    name = models.CharField('リハビリの内容', max_length=40)
    created_at = models.DateTimeField('日付', default=timezone.now)
    # models.ManyToManyFieldにて対応する

    def __str__(self):
        return self.name


class Comment(models.Model):
    name = models.CharField('コメント', max_length=400)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name


class KarteInfo(models.Model):
    patient = models.ForeignKey(
        Employee, on_delete=models.CASCADE, verbose_name='患者名')
    reha_at = models.DateField('リハビリ実施日', default=timezone.now)
    pain = models.ForeignKey(
        Pain,  on_delete=models.CASCADE, verbose_name='痛みの具合', blank=True)
    range = models.ForeignKey(
        Range,  on_delete=models.CASCADE, verbose_name='可動域制限', blank=True)
    rehaplan = models.ManyToManyField(
        RehaPlan, verbose_name='リハ内容', blank=True)
    comment = models.CharField('コメント', max_length=400)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return str(self.patient)

empmanager/karte/forms.py
from django import forms
from .models import KarteInfo

from django import forms
from .models import Employee, KarteInfo
from employee.models import Therapist



class KarteInfoSearchForm(forms.Form):
    therapist = forms.ModelChoiceField(
        queryset=Therapist.objects.all(), label='担当セラピスト', required=False)

    patient = forms.ModelChoiceField(
        queryset=Employee.objects.all(), label='患者名', required=False)

class KarteInfoSearchForm(forms.Form):
    therapist = forms.ModelChoiceField(
        queryset=Therapist.objects.all(), label='担当セラピスト', required=False)

    patient = forms.ModelChoiceField(
        queryset=Employee.objects.all(), label='患者名', required=False)


class KarteInfoForm(forms.ModelForm):
    reha_at = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = KarteInfo
        fields = ('patient', 'reha_at', 'pain', 'range', 'rehaplan', 'comment')
        widgets = {
            'rehaplan': forms.CheckboxSelectMultiple(),
        }


class AddPatientForm(forms.ModelForm):
    reha_at = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Employee
        fields = ['first_name', 'last_name', 'insurance', 'therapist']

empmanager/karte/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from employee.models import Therapist
from .models import KarteInfo
from .forms import KarteInfoForm, KarteInfoSearchForm, AddPatientForm
from employee.models import Employee

from django.views.generic import DetailView


class KarteInfoListView(ListView):
    model = KarteInfo
    template_name = 'karte/karteinfo_list.html'
    context_object_name = 'karte_info_list'
    paginate_by = 30
    form_class = KarteInfoSearchForm


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        for karteinfo in context['karte_info_list']:
            # KarteInfoに関連しているEmployeeの情報はドットで繋げることで取得できる！
            # print(karteinfo.patient.therapist)
            karteinfo.therapist = karteinfo.patient.therapist

        # フォーム情報を追加
        context['form'] = KarteInfoSearchForm(self.request.GET)

        # セラピストの一覧を取得
        context['therapist_all_list'] = Therapist.objects.all()

        return context

    def get_queryset(self):
        form = KarteInfoSearchForm(self.request.GET)
        form.is_valid()

        queryset = super().get_queryset()


        patient = form.cleaned_data['patient']
        if patient:
            queryset = queryset.filter(patient=patient)

        therapist = form.cleaned_data['therapist']
        if therapist:
            queryset = queryset.filter(patient__therapist=therapist)

        return queryset


# カルテ情報を追加する
class KarteInfoCreateView(CreateView):
    model = KarteInfo
    form_class = KarteInfoForm
    template_name = 'karte/karteinfo_form.html'
    success_url = reverse_lazy('karte:karteinfo_list')

class AddPatientCreateView(CreateView):
    model = Employee
    form_class = AddPatientForm
    template_name = 'karte/addpatient_form.html'
    success_url = reverse_lazy('karte:karteinfo_list')


class TherapistKarteListDetailView(DetailView):
    model = Therapist
    template_name = 'karte/therapistkartelist_detail.html'
    context_object_name = 'karte_detail_info_list'
    # form_class = KarteDetailInfoSearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        therapist = self.get_object()
        context['karte_detail_info_list'] = KarteInfo.objects.filter(patient__therapist=therapist)

        context['therapist_all_list'] = Therapist.objects.all()

        return context


class KarteInfoDetailView(DetailView):
    model = KarteInfo
    template_name = 'karte/karteinfo_detail.html'


class IdPatientKarteDetailView(DetailView):
    model = KarteInfo
    template_name = 'karte/id_patient_karte_detail.html'
    context_object_name = 'id_patient_karte_detail'
    paginate_by = 30

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient_id = self.kwargs['pk']
        context['id_karteinfo_list'] = KarteInfo.objects.filter(patient=patient_id)
        return context


empmanager/karte/templates/karte/addpatient_form.html
{% extends 'employee/base.html' %} {% block content %}

<p>
  <a href="{{ request.META.HTTP_REFERER }}"> 前のページへ戻る </a>
</p>

<h2 class="mb-5">患者登録フォーム</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="登録" />
</form>
{% endblock %}

empmanager/karte/templates/karte/id_patient_karte_detail.html
{% extends "employee/base.html" %} {% block content %}
<p>
  <a href="{{ request.META.HTTP_REFERER }}">
    前のページへ戻る
  </a>
</p>
{% if id_karteinfo_list.0.patient %}
<h2 class="karte-list-title mt-3 mb-5">
  {{ id_karteinfo_list.0.patient }}さんのカルテ一覧
</h2>

<!-- カルテ情報を表示するコード -->
<div class="table-responsive">
  <table class="table table-bordered mt-2">
    <thead>
      <tr>
        <th class="nowrap">ID</th>
        <th class="nowrap">患者名</th>
        <th class="nowrap">リハビリ実施日</th>
        <th class="nowrap">担当セラピスト</th>
        <th class="nowrap">痛みの具合</th>
        <th class="nowrap">可動域制限</th>
        <th class="nowrap">リハ内容</th>
        <th class="nowrap comment-area">リハコメント</th>
        <th class="nowrap">カルテ一覧</th>
        <th class="nowrap">患者詳細</th>
      </tr>
    </thead>
    <tbody>
      {% for karte_detail in id_karteinfo_list %}
      <tr>
        <td class="nowrap">{{ karte_detail.patient.id }}</td>
        <td class="nowrap">{{ karte_detail.patient }}</td>
        <td class="nowrap">{{ karte_detail.reha_at }}</td>
        <td class="nowrap">{{ karte_detail.patient.therapist.name }}</td>
        <td class="nowrap">{{ karte_detail.pain }}</td>
        <td class="nowrap">{{ karte_detail.range }}</td>
        <td class="nowrap">
          {% for plan in karte_detail.rehaplan.all %}
            {{ plan.name }}{% if not forloop.last %}、{% endif %}
          {% endfor %}
        </td>
        <td class="comment-area">{{ karte_detail.comment }}</td>
        <td class="nowrap">
          <a href="{% url 'karte:idpatientkarte_detail' pk=karte_detail.id %}"
            >⏩</a
          >
        </td>
        <td class="nowrap"><a href="{% url 'employee:idpatientinfo_detail' pk=karte_detail.id %}">⏩</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<h2 class="mt-5">まだカルテの情報がありません。</h2>
{% endif %} {% endblock content %}

empmanager/karte/templates/karte/karteinfo_form.html
{% extends 'employee/base.html' %} {% block content %}

<p>
  <a href="{{ request.META.HTTP_REFERER }}"> 前のページへ戻る </a>
</p>

<h2 class="mb-5">カルテ情報登録フォーム</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="登録" />
</form>
{% endblock %}

empmanager/karte/templates/karte/karteinfo_list.html
{% extends "employee/base.html" %} {% block content %}

<h2 class="karte-list-title mb-5">カルテ一覧</h2>

<div class="thera-detail mb-5">
  <p class="thera-detail-title mb-0">セラピスト個別ページ</p>
  <ul class="nav nav-tabs thera-detail-list">
    {% for thera in therapist_all_list %}
      <li class="nav-item thera-detail-item">
        <a
          href="{% url 'karte:therapistkartelist_detail' pk=thera.id %}"
          class="nav-link theradetail-link {% if thera.active %}active{% endif %}"
        >
          {{thera.name}}
        </a>
      </li>
    {% endfor %}
  </ul>
</div>


<form method="get" action="{% url 'karte:karteinfo_list' %}">
  {{ form }}
  <button type="submit">検索</button>
</form>

<div class="table-responsive">
  <table class="table table-bordered mt-2">
    <thead>
      <tr>
        <th class="nowrap">ID</th>
        <th class="nowrap">患者名</th>
        <th class="nowrap">リハビリ実施日</th>
        <th class="nowrap">担当セラピスト</th>
        <th class="nowrap">痛みの具合</th>
        <th class="nowrap">可動域制限</th>
        <th class="nowrap">リハ内容</th>
        <th class="nowrap comment-area">リハコメント</th>
        <th class="nowrap">カルテ一覧</th>
        <th class="nowrap">患者詳細</th>
      </tr>
    </thead>
    <tbody>
      {% for karte_info in karte_info_list %}
      <tr>
        <td class="nowrap">{{ karte_info.patient.id }}</td>
        <td class="nowrap">{{ karte_info.patient }}</td>
        <td class="nowrap">{{ karte_info.reha_at }}</td>
        <td class="nowrap">{{ karte_info.therapist.name }}</td>
        <td class="nowrap">{{ karte_info.pain }}</td>
        <td class="nowrap">{{ karte_info.range }}</td>
        <td class="nowrap">
          {% for plan in karte_info.rehaplan.all %}
            {{ plan.name }}
          {% endfor %}
        </td>
        <td class="comment-area">{{ karte_info.comment }}</td>
        <td class="nowrap"><a href="{% url 'karte:idpatientkarte_detail' pk=karte_info.patient.id %}">⏩</a></td>
        <td class="nowrap"><a href="{% url 'employee:idpatientinfo_detail' pk=karte_info.patient.id %}">⏩</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

empmanager/karte/templates/karte/therapistkartelist_detail.html
{% extends 'employee/base.html' %} {% block content %}
<h2 class="">{{ object }}さん担当：カルテ一覧</h2>

<hr class="mt-5 mb-2" />

<form action="" method='GET'>
  {{form}}
  <button type='submit'>検索</button>
</form>

<div class="thera-detail mb-2">
  <ul class="nav nav-tabs thera-detail-list">
    <li class="nav-item thera-detail-item">
      <a
        href="{% url 'karte:karteinfo_list' %}"
        class="nav-link theradetail-link {% if thera.active %}active{% endif %}"
      >
        カルテ一覧
      </a>
    </li>
    {% for thera in therapist_all_list %}
    <li class="nav-item thera-detail-item">
      <a
        href="{% url 'karte:therapistkartelist_detail' pk=thera.id %}"
        class="nav-link theradetail-link {% if thera.active %}active{% endif %}"
      >
        {{thera.name}}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>

{% if karte_detail_info_list %}
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>患者名</th>
        <th>リハビリ実施日</th>
        <th>痛みの具合</th>
        <th>可動域制限</th>
        <th>リハ内容</th>
        <th>リハコメント</th>
      </tr>
    </thead>
    <tbody>
      {% for karte_info in karte_detail_info_list %}
      <tr>
        <td>{{ karte_info.patient.id }}</td>
        <td>{{ karte_info.patient }}</td>
        <td>{{ karte_info.reha_at }}</td>
        <td>{{ karte_info.pain }}</td>
        <td>{{ karte_info.range }}</td>
        <td>
          {% for plan in karte_info.rehaplan.all %} {{ plan.name }} {% endfor %}
        </td>
        <td>{{ karte_info.comment }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% else %}
<h2>まだカルテの情報がありません。</h2>
{% endif %} {% endblock content %}