empmanager/employee/urls.py
from django.urls import path
from . import views


app_name = 'employee'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('detail/patient/<int:pk>', views.IdPatientInfoDetailView.as_view(), name="idpatientinfo_detail")
]

empmanager/empmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('karte/', include('karte.urls')),
    path('patient/', include('patient.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empmanager/karte/urls.py
from django.urls import path
from . import views

app_name = 'karte'

urlpatterns = [
    path('',views.KarteInfoListView.as_view(), name='karteinfo_list'),
    path('create/', views.KarteInfoCreateView.as_view(), name = 'karteinfo_create'),
    path('create/patient', views.AddPatientCreateView.as_view(), name = 'addpatient_create'),
    path('detail/therapist/<int:pk>', views.TherapistKarteListDetailView.as_view(), name='therapistkartelist_detail'),
    path('detail/karteinfo/<int:pk>', views.KarteInfoDetailView.as_view(), name='karteinfo_detail'),
    path('detail/karte/<int:pk>', views.IdPatientKarteDetailView.as_view(), name="idpatientkarte_detail")
]

empmanager/patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('', views.PatientInfoListView.as_view(), name='patientinfo_list'),
    path('add_excel_data/', views.AddExcelData .as_view(), name='add_excel_data'),
]

empmanager/employee/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class Insurance(models.Model):
  name = models.CharField('保険名', max_length=20)
  created_at = models.DateTimeField('日付', default=timezone.now)

  def __str__(self):
      return self.name

class Therapist(models.Model):
  name = models.CharField('セラピスト名', max_length=20)
  created_at = models.DateTimeField('日付', default=timezone.now)

  def get_absolute_url(self):
    return reverse('therapist_detail', args=[str(self.id)])

  def __str__(self):
      return self.name



class Employee(models.Model):
    first_name = models.CharField('名', max_length=20)
    last_name = models.CharField('姓', max_length=20)
    insurance = models.ForeignKey(Insurance, verbose_name='保険名', on_delete=models.PROTECT, null=True, blank=True)
    therapist = models.ForeignKey(Therapist, verbose_name='セラピスト名', on_delete=models.PROTECT, null=True, blank=True)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
      return '{0} {1}'.format(self.first_name, self.last_name)

    # def __str__(self):
    #     return self.name

    def save(self, *args, **kwargs):
        self.name = '{0} {1}'.format(self.first_name, self.last_name)
        super(Employee, self).save(*args, **kwargs)

empmanager/employee/forms.py
from django import forms
from .models import Therapist, Insurance, Employee

class SearchForm(forms.Form):
  therapist = forms.ModelChoiceField(
    queryset=Therapist.objects, label='セラピスト名', required=False
  )

  insurance = forms.ModelChoiceField(
    queryset=Insurance.objects, label='保険名', required=False
  )

class KarteDetailInfoSearchForm(forms.Form):
    patient_name = forms.CharField(max_length=255, required=False)
    patient = forms.ModelChoiceField(
        queryset=Employee.objects.all(), label='患者名', required=False)

empmanager/employee/views.py
from django.views import generic
from .forms import SearchForm, KarteDetailInfoSearchForm
from .models import Employee
from karte.models import KarteInfo


class IndexView(generic.ListView):
    model = Employee

    def get_context_data(self):
        context = super().get_context_data()
        context["form"] = SearchForm(self.request.GET)

        print("Context", context)

        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)
        form.is_valid()

        queryset = super().get_queryset()

        insurance = form.cleaned_data['insurance']
        if insurance:
            queryset = queryset.filter(insurance=insurance)

        therapist = form.cleaned_data['therapist']
        if therapist:
            queryset = queryset.filter(therapist=therapist)

        # print("Queryset", queryset)
        return queryset


class IdPatientInfoDetailView(generic.DetailView):
    model = Employee
    template_name = 'employee/id_patient_info_detail.html'
    context_object_name = 'id_patient_info'
    paginate_by = 30

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient_id = self.kwargs['pk']
        context['id_karteinfo_list'] = KarteInfo.objects.filter(
            patient=patient_id)
        context['id_employeeinfo_list'] = Employee.objects.filter(
            id=patient_id)
        context['form'] = KarteDetailInfoSearchForm()
        return context

    def get_queryset(self):
        form = KarteDetailInfoSearchForm(self.request.GET)
        form.is_valid()

        queryset = super().get_queryset()

        patient_name = form.cleaned_data['patient_name']
        if patient_name:
            queryset = queryset.filter(patient=patient_name)
            print("TTTTTTTTTTTTTTT", patient_name)

        print("Q QQQQQQQQQQQQQQQueryset", queryset)
        return queryset

empmanager/employee/templates/employee/base.html
{% load sass_tags %}

<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- SCSS -->
    <link rel="stylesheet" type="text/css" href="{% sass_src 'empmanager/scss/style.scss' %}" />



    <title>ばらシステム</title>
  </head>
  <body>
    <h1>ばらシステム</h1>

    <header class="header">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href={% url 'employee:index' %}>患者一覧</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'karte:karteinfo_list' %}">全てのカルテ一覧</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'karte:karteinfo_create' %}">カルテ情報を追加</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'karte:addpatient_create' %}">患者追加</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'patient:patientinfo_list' %}">新・患者一覧</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'patient:add_excel_data' %}">患者情報の追加・更新</a>
        </li>
      </ul>
    </header>

    <div class="container">
      {% block content %}

      {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

empmanager/employee/templates/employee/employee_list.html
{% extends "employee/base.html" %}
{% block content %}


<h2 class="mb-4">患者一覧</h2>

<form action="" method='GET'>
  {{form}}
  <button type='submit'>検索</button>
</form>
<table class="table table-bordered mt-2">
  <thead>
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>保険</th>
      <th>担当セラピスト</th>
      <th>カルテ一覧</th>
      <th>患者詳細</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employee_list %}
    <tr>
      <td>{{ employee.pk }}</td>
      <td>{{ employee }}</td>
      <td>{{ employee.insurance }}</td>
      <td>{{employee.therapist}}</td>
      <td><a href="{% url 'karte:idpatientkarte_detail' pk=employee.id %}">⏩</a></td>
      <td><a href="{% url 'employee:idpatientinfo_detail' pk=employee.id %}">⏩</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

empmanager/employee/templates/employee/home.html
{% extends "employee/base.html" %}
{% block content %}
<h2>HOME画面です</h2>
{% endblock content %}

empmanager/employee/templates/employee/id_patient_info_detail.html
{% extends "employee/base.html" %} {% block content %}
<p>
  <a href="{{ request.META.HTTP_REFERER }}">
    前のページへ戻る
  </a>
</p>
{% if id_karteinfo_list.0.patient %}
<h2 class="karte-list-title mt-3 mb-5">
  {{ id_karteinfo_list.0.patient }}さんの詳細情報
</h2>

<form action="" method='GET'>
  {{form}}
  <button type='submit'>検索</button>
</form>

<table class="table table-bordered mt-2">
  <thead>
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>保険</th>
      <th>担当セラピスト</th>

    </tr>
  </thead>
  <tbody>
    {% for employee in id_employeeinfo_list %}
    <tr>
      <td>{{ employee.pk }}</td>
      <td>{{ employee }}</td>
      <td>{{ employee.insurance }}</td>
      <td>{{employee.therapist}}</td>

    </tr>
    {% endfor %}
  </tbody>
</table>

<hr class="my-5">


<!-- カルテ情報を表示するコード -->
<div class="table-responsive">
  <table class="table table-bordered mt-2">
    <thead>
      <tr>
        <th class="nowrap">ID</th>
        <th class="nowrap">患者名</th>
        <th class="nowrap">リハビリ実施日</th>
        <th class="nowrap">担当セラピスト</th>
        <th class="nowrap">痛みの具合</th>
        <th class="nowrap">可動域制限</th>
        <th class="nowrap">リハ内容</th>
        <th class="nowrap comment-area">リハコメント</th>
        <th class="nowrap">カルテ一覧</th>
      </tr>
    </thead>
    <tbody>
      {% for karte_detail in id_karteinfo_list %}
      <tr>
        <td class="nowrap">{{ karte_detail.patient.id }}</td>
        <td class="nowrap">{{ karte_detail.patient }}</td>
        <td class="nowrap">{{ karte_detail.reha_at }}</td>
        <td class="nowrap">{{ karte_detail.patient.therapist }}</td>
        <td class="nowrap">{{ karte_detail.pain }}</td>
        <td class="nowrap">{{ karte_detail.range }}</td>
        <td class="nowrap">
          {% for plan in karte_detail.rehaplan.all %}
            {{ plan.name }}{% if not forloop.last %}、{% endif %}
          {% endfor %}
        </td>
        <td class="comment-area">{{ karte_detail.comment }}</td>
        <td class="nowrap">
          <a href="{% url 'karte:idpatientkarte_detail' pk=karte_detail.patient.id %}"
            >⏩</a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<h2 class="mt-5">まだカルテの情報がありません。</h2>
{% endif %} {% endblock content %}